api:
  autodiscoveryId: "123456"  

request:
  host: "0.0.0.0"
  port: "8083"
  method: "POST"
  path: "/api/nextgenemr"
  
https:
  host: "0.0.0.0"
  port: "8082"
  
tls:
  type: "JKS"
  path: "viva-keystore.jks"
  alias: "viva-cert"

