api:
  autodiscoveryId: "19824259"  

request:
  host: "viva-ng-sf-inbound-papi.us-e2.cloudhub.io"
  port: ""
  method: "POST"
  path: "/api/nextgenemr"
  
https:
  host: "0.0.0.0"
  port: "8082"
  
tls:
  type: "JKS"
  path: "viva-keystore.jks"
  alias: "viva-cert"

