#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    Patient_Race__c:
        type: string | nil 
        required: false
    Email:
        type: string
        required: true
    Marital_Status__c:
        type: string | nil 
        required: false
    FirstName:
        type: string
        required: false
    Patient_Gender__c:
        type: string | nil  
        required: false
    MailingCountry:
        type: string | nil 
        required: false
    MailingCity:
        type: string
        required: false
    type:
        type: string
        required: false
    MailingState:
        type: string
        required: false
    Date_of_Birth__c:
        type: date-only
        required: false
    Phone:
        type: string
        required: false
    HF_Chart_Number__c:
        type: string | nil 
        required: false
    MailingPostalCode:
        type: string
        required: false
    Patient_Ethnicity__c:
        type: string | nil 
        required: false
    Id:
        type: string
        required: false
    LastName:
        type: string
        required: false
    MailingStreet:
        type: string
        required: false
    Patient_Language__c:
        type: string | nil 
        required: false

