image: maven:3.8.2-jdk-8

stages:
  - build # Create a jar file
  - deploy # Deploy jar file to Cloudhub

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository


workflow:  # While deploying the applications, these variables are used to deploy it in respective environments
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev' || $CI_COMMIT_BRANCH =~ /^dev-.*/
      variables:
        ENVIRONMENT: "Development" 
        ENV: "dev"
        APP_NAME: "herself-sf-sys-delta-api-dev"
        BUCKET_NAME: "hh-dev-salesforce-s3"
      
    - if: $CI_COMMIT_BRANCH == 'release-candidate'
      variables:
        ENVIRONMENT: "Test" 
        ENV: "qa"
        APP_NAME: "herself-sf-sys-delta-api-qa"
        BUCKET_NAME: "hh-dev-salesforce-s3"
        


Build:
  stage: build 
  script:
    - echo "Building jar is started...."
    - echo "===========================\n It bulids the jar from artifacts......... \n ================================="
    - mvn -f "$POM_PATH" clean package # command for building jar file
    - echo "Building jar is completed....."
  only:
    - dev
    - dev-hotfix
    - release-candidate



Delpoying-to-dev: # This stage will triggered only after build stage 
  stage: deploy
  script:
    - echo "==========================\n Deploying process starts for dev \n ============================"
    
    - mvn -f "$POM_PATH" -Dusername="$ANYPOINT_USERNAME" -Dpassword="$ANYPOINT_PASSWORD" -DapplicationName="$APP_NAME" -Denvironment="$ENVIRONMENT" -DbusinessGroupId="$BUSSINESS_GROUP_ID" -Denv="$ENV" -Dkey="$KEY" -Dbatchsize="$BATCHSIZE" -Dbucketname="$BUCKET_NAME" -Dtimestampfromonetimeload="$TIMESTAMP_FROM_ONETIME_LOAD" -Dschedulertime="$SCHEDULER_TIME" -Dtls.host="$TLS_HOST_DEV" -DenableGlobalLogging="$ENABLEGLOBALLOGGING" deploy -DmuleDeploy

    - echo "==========================\n Deployed successfully in dev environment \n ==========================="
  
  only:
    - dev
    - dev-hotfix

Delpoying-to-qa: # qa environment is nothing but release-test environment
  stage: deploy
  script:
  
    - echo "==========================\n Deploying process starts for qa \n ============================"

    - mvn -f "$POM_PATH" -Dusername="$ANYPOINT_USERNAME" -Dpassword="$ANYPOINT_PASSWORD" -DapplicationName="$APP_NAME" -Denvironment="$ENVIRONMENT" -DbusinessGroupId="$BUSSINESS_GROUP_ID" -Denv="$ENV" -Dkey="$KEY" -Dbatchsize="$BATCHSIZE" -Dbucketname="$BUCKET_NAME" -Dtimestampfromonetimeload="$TIMESTAMP_FROM_ONETIME_LOAD" -Dschedulertime="$SCHEDULER_TIME" -Dtls.host="$TLS_HOST_QA" -DenableGlobalLogging="$ENABLEGLOBALLOGGING" deploy -DmuleDeploy

    - echo "==========================\n Deployed successfully in qa environment \n ============================"

  only:
    - release-candidate
