[{
  "Patient_Race__c": null,
  "Email": "sweetflore39@yahoo.com",
  "Marital_Status__c": null,
  "FirstName": "Marie-Flore",
  "Patient_Gender_2__c": "Female",
  "MailingCountry": null,
  "MailingCity": "BROOKLYN",
  "type": "Contact",
  "MailingState": "NY",
  "Date_of_Birth__c": "1976-08-15",
  "Phone": "(212) 470-5197",
  "HF_Chart_Number__c": null,
  "MailingPostalCode": "11236",
  "Patient_Ethnicity__c": null,
  "Id": "003Rj00000Buj14IAB",
  "LastName": "Bellevue.",
  "MailingStreet": "16-25 ROCKAWAY PARKWAY APT.2M",
}
]