#%RAML 1.0
title: viva-ng-sf-inbound-eapi
description: This API receives HL7 messages from NextGen EMR sends to the Process API.
version: v1
protocols: [HTTP,HTTPS]
mediaType: [text/plain,application/json]

securitySchemes:
  clientPolicy: !include /exchange modules/securityScheme.raml

/nextgenemr:
  displayName: nextgen API
  description: This resource handles the creation/updation of Contact and Appointment Object data in Salesforce
  securedBy: [ clientPolicy]
  post:
    body:
      text/plain:
        example: !include /examples/request.txt
    responses:
     200:
       body:
         text/plain:
           example: !include /examples/response.txt
     400:
       body:
         application/json:
           example: !include /examples/errorResponse.json
      
