#%RAML 1.0
title: viva-ng-sf-inbound-papi
description: This API receives HL7 messages and transforms the data and sends to the System API.
version: v1
protocols: [HTTP,HTTPS]
mediaType: [text/plain,application/json]

types:
  response-datatype : !include /datatypes/responseDataType.raml
  
/nextgenemr:
  displayName: nextgen API
  description: This resource handles the creation/updation of Contact and Appointment Object data in Salesforce

  post:
    body:
      text/plain:
        example: !include /examples/request.txt
    responses:
     200:
       body:
          application/json:
           example: !include /examples/response.json
           type: response-datatype
     400:
       body:
         application/json:
           example: !include /examples/errorResponse.json
      
