# Production environment configuration
mule.env: prod

# API configuration
api:
  autodiscoveryId: "123456"  

# HTTP settings
http:
  host: "0.0.0.0"
  port: "8083"

# HTTPS settings
https:
  host: "0.0.0.0"
  port: "8082"

# Request settings
request:
  host: "0.0.0.0"
  port: "8085"
  method: "POST"
  path: "/api/nextgenemr"
  
# TLS settings
tls:
  type: "JKS"
  path: "iewc-SSL-Keystore.jks"
  alias: "*.esb.internal.iewc.com"
  keypassword: test123
  password: test123

# Object Store settings for Production (persistent, will use OSv2 in CloudHub)
os:
  persistent: true
  directory: "/tmp"

# SF settings
sf:
  retryattempts: "3"
  retryfrequency: "30000"
  
# Email settings 
email:
  from: "viva.eve.notify@gmail.com"
  to: "cgainus@cokergroup.com"
  host: "smtp.gmail.com"
  port: "587"
  
  osv2.clientId: "4ac92be9ab7a4f6aaacaf3ac4ca198f3"
osv2.clientSecret: "385d4032B22349538557DBC1B9d871e2"
osv2.region: "us-east-1"