app:
  batchSize: "100"
  maxRetries: "3"
  retryDelayMs: "1000"
  
commonUtilities:
  loggingApi:
    host: "mule-worker-internal-common-utilities-api-dev.us-e2.cloudhub.io"
    port: "8092"

healthGorillaApi:
  host: "sandbox.healthgorilla.com"
  aud: "https://sandbox.healthgorilla.com/oauth/token"
  sub: "herselfhealth.api"
  
elationApi:
   host: "sandbox.elationemr.com"
  
aws:
  s3:
    bucket: "hh-dev-healthgorilla-harvest-documents"
    documentsFolder: "Documents"
    pollingFolder: "PatientPolling"
    pollingFrequency: "10"