app:
  batchSize: "100"
  maxRetries: "3"
  retryDelayMs: "1000"
  
commonUtilities:
  loggingApi:
    host: "mule-worker-internal-common-utilities-api-prod.us-e2.cloudhub.io"
    port: "8092"

healthGorillaApi:
  host: "api.healthgorilla.com"
  aud: "https://www.healthgorilla.com/oauth/token"
  sub: "herselfhealth.api"
  
elationApi:
  host: "app.elationemr.com"
  
aws:
  s3:
    bucket: "hh-prod-healthgorilla-harvest-documents"
    documentsFolder: "Documents"
    pollingFolder: "PatientPolling"
    pollingFrequency: "10"