elationApi:
  host: "sandbox.elationemr.com"

healthGorillaApi:
  host: "sandbox.healthgorilla.com"
  aud: "https://sandbox.healthgorilla.com/oauth/token"
  sub: "herselfhealth.api"
  
aws:
  s3:
    healthGorillaToHealthLake:
      bucket: "hh-dev-healthgorilla-to-healthlake"
      pollingFolder: "PatientPolling"
    healthGorillaToElation:
      bucket: "hh-dev-healthgorilla-to-elation"
      pollingFolder: "PatientPolling"
    healthGorillaHarvestDocuments:
      bucket: "hh-dev-healthgorilla-harvest-documents"
      pollingFolder: "PatientPolling"
  rds:
    interopDatabase:
      host: "hh-sql-database-dev.ckgj59svd8dx.us-east-1.rds.amazonaws.com"
      port: "1433"
      database: "hh_interop_dev"
  snowflake:
    accountName: "ab16868.us-east-2.aws"
    database: "DEV_HERSELF"
    schema: "ROSTER"