elationApi:
  clientId: "![XCb+ti6m6ZoOy/Su03f8fQWfD+wVjHubt3j+i+d4yy7nsf0HwT6kvlr5coNjrimn]"
  clientSecret: "![iTV6L3oxrYnZglVwPLvRFhMs1uJIHEZo3JP9R0D1h8vpfqRmMWEZALGetRks9Rwa1z8HjKoSSmMpEYPQ0bbjzMN2uIIQqQvfTmZDNtzWbmCu9EGo3sRj2pyOLwLjm3p4kX++ZgM6QW0=]"

healthGorillaApi:
  clientId: "![VwRqc9v5AO65d+4vXuEVzt9KO3BN0NffwK6iRG21CannejoTBQn28p4ER+qu9n1o]"
  clientSecret: "![4wvIbP8KimWIUmSM+2FUiitg1Of4LUnHNb63x7QXG0SQXw+Yz06MI7hgi4H7ZPDX]"
  
aws:
  rds:
    interopDatabase:
      user: "![WEWoyLRmzBU=]"
      password: "![uuwqvbOV6stKQ4M8aCUhSw==]"
  snowflake:
    user: "![xQGwcMcYutiYlXttWEnz84OKkSLb7sEANyEKWIUtDD0=]"
    password: "![wPFUm7lI7uZWX27C6KOfDw==]"