minnesotaAdt:
  sftp:
    username: "![7AZFFAaGblt8uyFuMsnmKQ==]"
    password: "![Ez4LYAFxveQfSiBIxEhuoA==]"
    
bambooHealth:
  sftp:
    username: "![XQj8QFkX/79tPcM8/LayN2rAkyFJeONd]"
    password: "![1r25NDZ91MZV7gR6gT/r5sKTUGe3Lgy0]"
    
aws:
  snowflake:
    user: "![xQGwcMcYutiYlXttWEnz84OKkSLb7sEANyEKWIUtDD0=]"
    password: "![wPFUm7lI7uZWX27C6KOfDw==]"
    