elationApi:
  host: "app.elationemr.com"

healthGorillaApi:
  host: "api.healthgorilla.com"
  aud: "https://www.healthgorilla.com/oauth/token"
  sub: "herselfhealth.api"
  
aws:
  s3:
    healthGorillaToHealthLake:
      bucket: "hh-prod-healthgorilla-to-healthlake"
      pollingFolder: "PatientPolling"
    healthGorillaToElation:
      bucket: "hh-prod-healthgorilla-to-elation"
      pollingFolder: "PatientPolling"
    healthGorillaHarvestDocuments:
      bucket: "hh-prod-healthgorilla-harvest-documents"
      pollingFolder: "PatientPolling"
  rds:
    interopDatabase:
      host: "hh-sql-database-prod.cvvqp5ertig9.us-east-1.rds.amazonaws.com"
      port: "1433"
      database: "hh_interop_prod"
  snowflake:
    accountName: "ab16868.us-east-2.aws"
    database: "HERSELF"
    schema: "ROSTER"
