sf:
  pwd: "![s1Y+XyxS4gLfhtUJ93htZ2i3q7a9leTI]"  
  token: "![/a5KV7zCXt5hO/S0tgnOlJ/pal2BL2ulzAk2u7U6GZM=]"

aws:
  rds:
    interopDatabase:
      user: "![8nvgUp+woKw=]"
      password: "![cZW7mVaA6kn2oOZF3O4c4w==]"
  snowflake:
      user: "![njKyVPJDkv8=]"  
      password: "![KP5uPQAZCv4OSUNS0hHgQg==]"