# Common File to be use in All env
application:
  name: "viva-ng-sf-inbound-papi"
  
source: "viva-ng-sf-inbound-papi"
target: "salesforce"
 
# Logger
logger:
  category:
    payload: "com.prowess.integration.logging.payload"
    milestones: "com.prowess.integration.logging.milestones"

milestone:
  cateogry: "LOG"
  requetReceived: "RequestReceived"
  requetSent: "RequetSent"
  successResponseReceived: "SuccessResponseReceived"
  successResponseSent: "SuccessResponseSent"