api:
  autodiscoveryId: "123456"  

http:
  host: "0.0.0.0"
  port: "8083"
  
https:
  host: "0.0.0.0"
  port: "8082"
  
request:
  host: "0.0.0.0"
  port: "8085"
  method: "POST"
  path: "/api/nextgenemr"  
 
tls:
  type: "JKS"
  path: "iewc-SSL-Keystore.jks"
  alias: "*.esb.internal.iewc.com"
  keypassword: test123
  password: test123